### ISSUE TITLE
feat: support for touch moves

### ISSUE THREAD

**Issue by suterma** [slipmatio/control-knob#16]
Currently the knob does support mouse drags, mouse wheel events and up/down keys. On touch screens however, the value can not currently be changed. This feature should bring touch support similar to mouse drags.

@Uninen: I have already a solution for this in my fork's main repo. You might take it from there or, if you prefer, I can create a PR in a separate feature branch.

**Comment by Uninen** [comment]
This would be greatly appreciated -- feel free to do a PR, I'm happy to merge it 👍

**Comment by suterma** [comment]
I am going to create a PR, possibly over the weekend.

**Comment by suterma** [comment]
PR is ready, please merge or comment: https://github.com/slipmatio/control-knob/pull/19
