### ISSUE TITLE
Mouse wheel and keyboard also does scroll the page vertically

### ISSUE THREAD

**Issue by suterma** [slipmatio/control-knob#8]
First: Great component, great styling options, and many thanks for sharing.

Problem:
However, the mouse wheel and keyboard support is not perfect. Although it works ( can change the value with both the mouse wheel, when hovering, and the up/down arrow keys when focused), the page ALSO gets vertically scrolled at the same time.
This does not happen with the "precise" mode, using the shift keys, probably because these are not handled at the page level anyway.

Possible solution:
There should be, by default, no further propagation of these events, so that scrolling does not occur by default. 

This should be configurable however, since it is conceivable that someone wants to handle these events outside.

**Comment by Uninen** [comment]
Thanks for the report! I’ll take a look at this and figure put a way to add some tests as well.

**Comment by suterma** [comment]
This seems a relevant blog post for a solution: https://alvarotrigo.com/blog/prevent-scroll-on-scrollable-element-js/
